/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {},
    },
    plugins: [require('daisyui')],
    daisyui: {
        themes: [
            "light",
            "bumblebee",
            "forest",
            "lofi",
            "fantasy",
            "cmyk",
            "autumn",
            "acid",
            "lemonade",
            "winter",
            "halloween",
            "valentine",

            // Commented out themes (uncomment to re-enable):
            // "dark",
            // "cupcake",
            // "emerald",
            // "corporate",
            // "synthwave",
            // "retro",
            // "cyberpunk",
            // "valentine",
            // "aqua",
            // "black",
            // "luxury",
            // "dracula",
            // "business",
            // "night",
            // "coffee",
            // "dim",
            // "nord",
            // "sunset",
        ],
        darkTheme: "dark",
        base: true,
        styled: true,
        utils: true,
    },
}
